// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqswbsipmqgowqtaghoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxc3dic2lwbXFnb3dxdGFnaG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTM2NzAsImV4cCI6MjA2MDY2OTY3MH0.cYZ0TfUdwDE-0wQ0t0fcYiHc43MhV9fAQ7bIptG5Kyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);